apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 55.5.0   # check latest
    helm:
      releaseName: monitoring
      values: |
        grafana:
          enabled: true
          adminUser: admin
          adminPassword: password
          service:
            type: LoadBalancer
        prometheus:
          prometheusSpec:
            retention: 10d
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
