apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-secret-generator
  namespace: monitoring
spec:
  template:
    spec:
      serviceAccountName: grafana-secret-sa
      restartPolicy: Never
      containers:
        - name: secret-generator
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              if ! kubectl get secret grafana-admin-credentials -n monitoring >/dev/null 2>&1; then
                PASSWORD=$(openssl rand -base64 20)
                kubectl create secret generic grafana-admin-credentials \
                  -n monitoring \
                  --from-literal=admin-user=admin \
                  --from-literal=admin-password=$PASSWORD
              else
                echo "Secret already exists, skipping."

