apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-secret-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-secret-role
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-secret-rolebinding
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: grafana-secret-sa
    namespace: monitoring
roleRef:
  kind: Role
  name: grafana-secret-role
  apiGroup: rbac.authorization.k8s.io
